apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastfood-ingress
  namespace: fastfood
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
    alb.ingress.kubernetes.io/success-codes: "200"
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:

          # =====================
          # CATALOG MS
          # =====================
          - path: /v1/categories
            pathType: Prefix
            backend:
              service:
                name: fastfood-catalog-ms
                port:
                  number: 8080

          - path: /v1/customers
            pathType: Prefix
            backend:
              service:
                name: fastfood-catalog-ms
                port:
                  number: 8080

          - path: /v1/employees
            pathType: Prefix
            backend:
              service:
                name: fastfood-catalog-ms
                port:
                  number: 8080

          - path: /v1/products
            pathType: Prefix
            backend:
              service:
                name: fastfood-catalog-ms
                port:
                  number: 8080

          # =====================
          # ORDERS MS
          # =====================
          - path: /v1/orders
            pathType: Prefix
            backend:
              service:
                name: fastfood-orders-ms
                port:
                  number: 8080

          - path: /v1/combos
            pathType: Prefix
            backend:
              service:
                name: fastfood-orders-ms
                port:
                  number: 8080

          # =====================
          # PAYMENTS MS
          # =====================
          - path: /v1/payments
            pathType: Prefix
            backend:
              service:
                name: fastfood-payments-ms
                port:
                  number: 8080

          - path: /v1/webhooks
            pathType: Prefix
            backend:
              service:
                name: fastfood-payments-ms
                port:
                  number: 8080
